App/models/workout.py
from App.database import db

class Workout(db.Model):
    workoutId = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False)
    type = db.Column(db.String(200), nullable=False)
    muscle = db.Column(db.String(200), nullable=False)
    equipment = db.Column(db.String(200), nullable=False)
    difficulty = db.Column(db.String(200), nullable=False)
    instructions = db.Column(db.String(100000), nullable=False)

    def __init__(self, name, type, muscle, equipment, difficulty, instructions):
        self.name = name
        self.type = type
        self.muscle = muscle
        self.equipment = equipment
        self.difficulty = difficulty
        self.instructions = instructions

    def __repr__(self):
        return f'<Workout {self.workoutId} - {self.name} - {self.difficulty} - {self.type}>' 

    def toJSON(self):
        return {
            'workoutId': self.workoutId,            
            'name': self.name,
            'type': self.type,
            'muscle': self.muscle,
            'equipment': self.equipment,
            'difficulty': self.difficulty,
            'instructions': self.instructions,            
        }


App/controllers/myworkout.py
from App.models import UserWorkout, Workout, User
from App.database import db
from App.config import config

import requests
import json


def save_workout(userId, workoutId,name,sets, reps, weight, day,pub):
  w = Workout.query.filter_by(workoutId=workoutId).first()

  if weight is None or weight == "":
    if w.equipment not in ["other", "body_only", "body"]:
        weight = "10lbs"
    else:
        weight = "body"
  try: 
    workout = UserWorkout(userId = userId, workoutId = workoutId,name=name ,sets = sets, reps=reps, weight = weight,day = day,pub=pub)
    user = User.query.filter_by(id=userId).first()
    db.session.add(workout)   
    user.workouts.append(workout)   
    db.session.commit()
    return workout
  except:
    return None


def edit_workout(uwId,userId,name,sets,reps,weight,day,pub):
  workout = UserWorkout.query.filter_by(uwId = uwId, userId=userId).first()  
  if workout:
    if not name:
      name = workout.name
    if not sets:
      sets = workout.sets
    if not reps:
      reps = workout.reps
    if not weight: 
      weight =workout.weight
    if not day:
      day = workout.day 

    if pub is None:
      pub = workout.pub

    try: 
      workout.name = name
      workout.sets = sets
      workout.reps = reps
      workout.weight = weight
      workout.day = day
      workout.pub = pub
      db.session.add(workout)
      db.session.commit()
      return True
    except: 
      return None
  return None


def delete_workout(uwId,userId):
  workout = UserWorkout.query.filter_by(uwId = uwId, userId=userId).first()
  if workout:
    try:
      db.session.delete(workout)
      db.session.commit()
      return True
    except: 
      return None
  return None

def get_workouts_by_day(userId,day):
  user = User.query.filter_by(id=userId).first()
  if user: 
      workout = UserWorkout.query.filter_by(day = day, userId=user.id).all()      
      return workout
  else:
    return None

def get_all_user_workouts():
  return UserWorkout.query.all()

def get_user_workouts(userId):
  return UserWorkout.query.filter_by(userId=userId).all() 

def get_listing():
  return UserWorkout.query.filter_by(pub=True).all()

def save_listing_workout(uwId, userId):
  workout = UserWorkout.query.filter_by(uwId=uwId).first()
  if workout is None:
      return None
  if workout.userId == userId:
      return None
  else:
    try:
      new_workout = UserWorkout(name=workout.name,
                                workoutId=workout.workoutId,
                                sets=workout.sets,
                                reps=workout.reps,
                                weight=workout.weight,
                                day=workout.day,
                                userId=userId,
                                pub=False)
      db.session.add(new_workout)
      db.session.commit()
      return new_workout
    except:
      return None



  
 
    

App/views/allworkouts.py
from flask import Blueprint, redirect, render_template, request, send_from_directory, jsonify, json, flash
import requests
from flask_login import current_user
allworkouts_views = Blueprint('allworkouts_views', __name__, template_folder='../templates')
from App.controllers import (
    get_workout,
    user_required,
    get_listing,
    get_all_workouts,
    save_listing_workout,
    get_all_users
)

@allworkouts_views.route('/allworkouts', methods=['GET'])
@user_required
def allworkouts_page():
    allexercises = {
        "Muscle Group": {
            "abdominals": "https://i.imgur.com/ITkNaQF.jpg",
            "chest": "https://i.imgur.com/64E9dwe.jpg",
            "glutes": "https://i.imgur.com/akYHUfu.jpg",
            "biceps": "https://i.imgur.com/8CbLSfK.jpg",
            "quadriceps": "https://i.imgur.com/JkFAUR4.jpg",
            "lower_back": "https://i.imgur.com/XZ28MRQ.jpg",
            "abductors": "https://i.imgur.com/zSszIKa.jpg",
            "calves": "https://i.imgur.com/ae5g2vw.jpg",
            "hamstrings": "https://i.imgur.com/nwMI9X9.jpg"
        },
        
        "Difficulty": {
            "beginner": "https://i.imgur.com/Q591BDn.jpg",
            "intermediate": "https://i.imgur.com/yj68wj9.jpg",
            "expert": "https://i.imgur.com/ahtB3nB.jpg"
        },
        "Type": {
            "cardio": "https://i.imgur.com/KunmoF9.jpg",
            "plyometrics": "https://i.imgur.com/s7Ixets.jpg",
            "strength": "https://i.imgur.com/O8gPRcQ.jpg",
            "stretching": "https://i.imgur.com/DcqbcjV.jpg",
            "strongman": "https://i.imgur.com/itYgSYL.jpg",
            "powerlifting": "https://i.imgur.com/km1LYQY.jpg"
        }
    }

    return render_template('allworkouts.html',allexercises = allexercises)

@allworkouts_views.route('/listing', methods=['GET'])
@user_required
def listing_page():
    workouts = get_all_workouts()
    listing = get_listing()
    users = get_all_users()
    return render_template('listing.html',listing=listing,workouts=workouts, users =users)

@allworkouts_views.route('/savelisting/<int:uwId>', methods=['GET'])
@user_required
def listing_action(uwId):
    workout = save_listing_workout(uwId,current_user.id)    
    if workout:
        flash('Successfully Saved!' + " " + workout.name)
    else:
        flash('Already Saved!')
    return redirect(request.referrer)

@allworkouts_views.route('/search', methods=['GET'])
@user_required
def searchWorkouts_page():
    query = request.args.get('query')    
    workouts = get_workout(query)
    w_days = {"Monday": "Monday", "Tuesday": "Tuesday", 
    "Wednesday": "Wednesday", "Thursday": 
    "Thursday", "Friday": "Friday", 
    "Saturday": "Saturday", "Sunday": "Sunday"}
    return render_template('search.html', workouts=workouts, search=query,w_days=w_days) 

App/views/myworkouts.py
from flask import Blueprint, redirect, render_template, request, send_from_directory, jsonify, json, flash
import requests
from flask_login import current_user
myworkouts_views = Blueprint('myworkouts_views', __name__, template_folder='../templates')

from App.controllers import (
    get_workouts_by_day,
    edit_workout,
    delete_workout,
    user_required,
    get_all_workouts
)


@myworkouts_views.route('/myworkouts', methods=['GET'])
@user_required
def myworkouts_page():

    w_workouts = ["mon", "tue","wed","thu","fri","sat" ,"sun"]
    week_workouts = [
        "Monday", 
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday"
    ]

    workouts_dict = {}
    for day in week_workouts:
        workouts_dict[week_workouts[week_workouts.index(day)]] = get_workouts_by_day(current_user.id, day)
    workouts = get_all_workouts()

    w_days = {"Monday": "Monday", "Tuesday": "Tuesday", 
    "Wednesday": "Wednesday", "Thursday": 
    "Thursday", "Friday": "Friday", 
    "Saturday": "Saturday", "Sunday": "Sunday"}
    return render_template('myworkouts.html', days = workouts_dict, workouts = workouts, w_days=w_days)

@myworkouts_views.route('/myworkouts', methods=['POST'])
@user_required
def editWorkout():
    data = request.form
    if not data.get('pname'):
        pname = None
    else:
        pname = data.get('pname')

    if not data.get('sets'):
        sets = None
    else:
        sets = data.get('sets')

    if not data.get('reps'):
        reps = None
    else: 
        reps = data.get('reps')

    if not data.get('day'):
        day = None
    else:
        day = data.get('day')

    if not data.get('weight'):
        weight = None
    else:
        weight = data.get('weight')

    pub = None
    rempublic = request.form.get('public') == 'remove'
    addpublic = request.form.get('public') == 'add'

    if rempublic:
        pub = False
    elif addpublic:
        pub = True
        
    new_workout = edit_workout(data["workoutId"],current_user.id,pname, sets, reps, weight, day,pub)
    if(new_workout):
        flash("Successfully Edited!")        
        return redirect(request.referrer)
    else:
        return redirect(request.referrer)


@myworkouts_views.route('/myworkouts/<int:uwid>', methods=['GET'])
@user_required
def deleteWorkout(uwid):
    if delete_workout(uwid,current_user.id):
        flash("Successfully Deleted!")        
        return redirect(request.referrer)



App/views/workout.py
from flask import Blueprint, redirect, render_template, request, send_from_directory, jsonify, flash
from flask_login import current_user

workout_views = Blueprint('workout_views', __name__, template_folder='../templates')
from App.controllers import (
    save_workout,
    get_all_workouts1,
    get_workout_by_id,
    user_required
)

@workout_views.route('/workout', methods=['POST'])
@user_required
def saveWorkout():
  data = request.form 
  pub = request.form.get('public') == 'on'
  print(current_user.id) 
  new_workout = save_workout(current_user.id, data["workoutId"],data["pname"],data["sets"], data["reps"], data["weight"], data["day"],pub)  
  flash('Successfully Saved' + " " + data["pname"])
  return redirect(request.referrer)


@workout_views.route('/workouts/<value>', methods=['GET'])
@user_required
def workout_page(value):

    type_group = ["cardio", "plyometrics", "strength","stretching","strongman","powerlifting"]
    muscle_group  = ["abdominals", "biceps", "chest","glutes","quadriceps","lower_back","abductors","calves", "hamstrings"]
    difficulty_group = ["beginner", "intermediate", "expert"]
    muscle = None
    workout_type = None
    difficulty = None
    if value in muscle_group:
      muscle = value
    elif value in type_group:
      workout_type = value
    elif value in difficulty_group:
      difficulty = value
   
    w_days = {"Monday": "Monday", "Tuesday": "Tuesday", 
    "Wednesday": "Wednesday", "Thursday": 
    "Thursday", "Friday": "Friday", 
    "Saturday": "Saturday", "Sunday": "Sunday"}
    workouts = get_all_workouts1(muscle=muscle, workout_type=workout_type, difficulty=difficulty)    
    return render_template('workout.html', workouts=workouts, value=value.title(), w_days=w_days)
   

App/templates/allworkouts.html
{% extends "layout.html" %}
{% block title %}All Exercises{% endblock %}
{% block page %}All Exercises{% endblock %}

{% block content%}
<div class="parallax-container" id="banner">
    <div class="parallax responsive-img"><img src="https://i.imgur.com/Xxu1g1u.jpg"></div>    
    <div class="section" id="top-section">
      <div class="container">
        <div class="row">
          <div class="col s12 m6">
            <img src="" class="responsive-img">
          </div>
          <div class="col s12 m6">
            <h3 class="center-align white-text">All Exercises</h3>
            <p class="center-align white-text">Get fit with our collection of workouts!</p>
            <div class="center-align">
              <a href="/listing" class="waves-effect waves-light btn grey lighten-1">See Created Workouts</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<main>
      {% for key, value in allexercises.items() %}
        {% if key == 'Difficulty' %}
        <section class="section blue-grey lighten-5">
        {%else%}
        <section class="section">
            {%endif%}
          <div class="container">              
                  <h3>{{ key|title }}</h3>                  
                  <div class="row">
                      {% for exercise, img_link in value.items() %}
                          <div class="col s12 m4">
                              <div class="card hoverable">
                                  <div class="card-image">
                                      <img class="exercise-img" src="{{ img_link }}">
                                      <a id="actbtn" class="btn-floating halfway-fab waves-effect waves-light" href="{{ url_for('workout_views.workout_page', value=exercise) }}" ><i class="material-icons">arrow_forward</i></a>
                                    </div>
                                    <div class="card-footer" id ="all_workouts">
                                      {%if exercise == 'lower_back'%}
                                      <span class="card-title white-text" >Lower Back</span>
                                      {%else%}
                                      <span class="card-title white-text " >{{ exercise|title }}</span>
                                      {%endif%}
                                  </div>
                                  
                              </div>
                          </div>
                      {% endfor %}
                     
                  </div>
                  <br>
                  <br>
              
          </div>
      </section>
{% endfor %}
</main>
<div class="parallax-container" id="banner_b">
  <div class="parallax responsive-img"><img src="https://i.imgur.com/Xxu1g1u.jpg"></div>      
</div>
{%endblock%}

App/templates/home.html
{% extends "layout.html" %}
{% block title %}Home{% endblock %}
{% block page %}Home{% endblock %}

{% block content%}
<main>
<div class="parallax-container">
	<div class="parallax"><img src="https://i.imgur.com/hOiN5DN.jpg"></div>			
</div>
	
	<div  class= "container"  >
		<div class="row" >
			<div class="col s12 m6">
				<h2>Get Fit with Our Workouts</h2>
				<p>Your only limit is the one you set for yourself. Believe in yourself, push past the pain, and achieve the impossible.</p>				
				<form method="GET" action="{{ url_for('allworkouts_views.searchWorkouts_page')}}" id="searchForm">
					<div class="input-field rounded" id="homesearch">
						<input type="text" id="search" name="query" required>
						<label class="label-icon" for="serach"><i class="material-icons">search</i></label>						
					</div>
				</form>
			</div>
		</div>
	</div>
  <div class="parallax-container">
    <div class="parallax"><img src="https://imgur.com/F5zX4Pt.jpg"></div>  
</div>
</main>
{% endblock %}


App/templates/layout.html
<!doctype html>
<html>
  <head>
  
     <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Congenial+Italic&display=swap" rel="stylesheet">

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>{% block title %}{% endblock %}</title>
    {% block styles %}

    {% endblock %}
    <link rel="stylesheet" href="/static/style.css">
    <style type="text/css">
      #loader {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: #2e2e2e;
        display: flex;
        align-items: center;
        justify-content: center;
        z-index: 9999;
      }
      #loader .preloader-wrapper {
        display: inline-block;
        position: relative;
        width: 80px;
        height: 80px;
      }
      #loader .preloader-wrapper.active {
        animation: spinner-linear 1.1s cubic-bezier(0.3, 0.6, 1, 1) infinite;
      }
      #loader .spinner-layer {
        position: absolute;
        width: 100%;
        height: 100%;
        opacity: 0;
        border-color: #FF3131;
        border-style: solid;
        border-width: 4px;
        border-radius: 50%;
        -webkit-animation: fade-in-spinner 1.5s ease-in-out infinite;
        animation: fade-in-spinner 1.5s ease-in-out infinite;
      }
      #loader .spinner-layer.active {
        opacity: 1;
      }
      @keyframes fade-in-spinner {
        0% {
          opacity: 0;
        }
        50% {
          opacity: 1;
        }
        100% {
          opacity: 0;
        }
      }
      @keyframes spinner-linear {
        0% {
          transform: rotate(0deg);
        }
        100% {
          transform: rotate(360deg);
        }
      }

      
    </style>
  </head>
  <body>  
    <div id="loader">
      <div class="preloader-wrapper big active">
        <div class="spinner-layer spinner-blue-only">
          <div class="circle-clipper left">
            <div class="circle"></div>
          </div>
          <div class="gap-patch">
            <div class="circle"></div>
          </div>
          <div class="circle-clipper right">
            <div class="circle"></div>
          </div>
        </div>
      </div>
    </div>  
      
    <nav class="black" role="navigation">
      <div class="nav-wrapper container">        
        <a href="/home"><img class="brand-logo" src="https://i.imgur.com/P7mALVJ.png" title="source: imgur.com" /></a>
        {% if current_user.is_authenticated %}
        <ul class="right hide-on-med-and-down">
          <li><a href="/home">Home</a></li>
            <li><a href="/allworkouts">All Exercises</a></li>
            <li><a href="/myworkouts">My Workouts</a></li>
            <li>          
              <form  method="GET" action="{{ url_for('allworkouts_views.searchWorkouts_page')}}" id="searchForm">
                <div class="input-field">
                  <input id="navbar-search" type="search" name="query" required>
                  <label class="label-icon" for="navbar-search"><i class="material-icons">search</i></label>
                  <i class="material-icons clear-icon">close</i>
                </div>
              </form>
            </li>
            <li><a href="/logout">Logout</a></li>
        </ul>
  
        <ul id="nav-mobile" class="sidenav">
          <li><a href="/home">Home</a></li>
          <li><a href="/allworkouts">All Exercises</a></li>
          <li><a href="/myworkouts">My Workouts</a></li>      
          <li><a href="/logout">Logout</a></li>
        </ul>
        <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      </div>
      {%endif%}
    </nav>
    
    <div class="messages">
      {% with messages = get_flashed_messages() %}
      {% if messages %}
      <div id="alert" class="col s10 offset-s1">
        <a href="" id="close">&times;</a>
        {% for message in messages %}
        <div style="font-weight: bold;text-align: center;font-size: 1.2em;margin-top: -5px;">{{ message }}</div>
        {% endfor %}
      </div>

      {% endif %}
      {% endwith %}
    </div>

    

    <div id="content" >{% block content %}{% endblock %}</div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
        M.AutoInit();
        window.onload = function() {
    // Hide the preloader after a few seconds
    setTimeout(function() {
        document.getElementById('loader').style.display = 'none';
    }, 1000); // 3000 milliseconds = 3 seconds
}

  function checkPasswords() {
    var password = document.getElementById("password").value;
    var confirm_password = document.getElementById("confirm_password").value;
    if (password != confirm_password) {
      alert("Passwords do not match.");
      return false;
    }
    return true;
  }

    </script>
    <script src="/static/main.js"></script>
    
  </body>
  <footer class="page-footer black darken-3">
    <div class="">
      <div class="row left-align">
        <div class="col s12 m3"> 
            <h4>About US</h4>                  
            <p>Welcome to FitX, the ultimate destination for fitness enthusiasts who love to mix up their workouts and keep things fresh and exciting!</p>
            <p>Our website is dedicated to providing you with the tools and resources you need to create your own customized workout playlists and remixes, so you can stay motivated and inspired to reach your fitness goals.</p>            
        </div>
        <div class="col s12 m3 center-align">
          <div class="">
            <h5 class="white-text">Links</h5>
            <ul>
              <li><a href="/home">Home</a></li>
              <li><a href="/allworkouts">Workouts</a></li>
              <li><a href="#">Contact</a></li>
              <li><a href="https://github.com/xFit-X/FitX-app" target="_blank">GitHub</a></li>
            </ul>
          </div>
        </div>
        <div class="col s12 m3 center-align">          
          <a href="/home"><img class="logo-img" src="https://i.imgur.com/P7mALVJ.png" title="source: imgur.com" /></a>
          <ul>
            <li><i class="material-icons">location_on</i> UWI St. Augustine</li>
            <li><i class="material-icons">phone</i> 123-4567</li>
            <li><i class="material-icons">email</i> support@fitx.com</li>
          </ul>
        </div>
        
        <div class="col s12 m3">
          <div class="center-align">
            <h5 class="white-text">Download our App FitX</h5>
            <div>
              <a href="/home"><img src="https://i.imgur.com/HTZA9N2.png" title="source: imgur.com" /></a>           
            </div>
          </div>
        </div>       
      </div>
    </div>
    <div class="grey darken-3">
      <div class="container">        
        <div class="row">
          <div class="col s12">
            <p class="center-align white-text">&copy; 2023 Workout Website. All rights reserved.</p>
          </div>
        </div>
      </div>
    </div>
  </footer>  
</html>

App/templates/login.html
{% extends "layout.html" %}

{% block title %}FitX{% endblock %}

{% block page %}FitX{% endblock %}


{% block content %}

<main class="container">
<div class="row center-align" >
  <div class="col s12 m6 offset-m3" >
    <div class="card">
      <div class="card-content">
        <span class="card-title center">Login</span>
        <form id="loginForm" method="POST" action="/login" style="padding:1em">
          <div class="row">
            <div class="input-field col s12">              
              <input id="username" name="username" type="text" class="validate" style="border-radius: 20px; border: 2px solid #ccc;">
              <label for="username" >Username</label>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s12">
              <input name="password" id="password" type="password" class="validate" style="border-radius: 20px; border: 2px solid #ccc;">
              <label for="password">Password</label>
            </div>
          </div>
          <div class="row justify-content">
            <div class="center">
              <input type="submit" class="black text-white btn" value="Sign In">
            </div>
            <br>
            <div class="center">
              <a href="/signup">New to FitX? Sign Up</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
</main>

{% endblock %}

App/templates/myworkouts.html
{% extends "layout.html" %}
{% block title %}My Workouts{% endblock %}
{% block page %}My Workouts{% endblock %}

{% block content%}

<div class="parallax-container" id="banner">
  <div class="parallax"><img src="https://i.imgur.com/W8LXHbD.jpg"></div>
  <div class="section" id="top-section">
    <div class="container">
      <div class="row">
        <div class="col s12 m6">
          <img src="" class="responsive-img">
        </div>
        <div class="col s12 m6">
          <h3 class="center-align white-text">Daily Workouts</h3>
          <p class="center-align white-text">Your collection of workouts to keep you fit and healthy all week long!</p>
          <div class="center-align">
            <a href="/listing" class="waves-effect waves-light btn grey lighten-1">See Created Workouts</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<main >
  <br>
  <br>    
        <ul class="collapsible popout reponsive" >
          {% for day, work in days.items() %}
          <li>
            <div class="collapsible-header" >{{ day }}</div>
            <div class="collapsible-body" >
              <ul>
                {% for workout in work %}
                {% for w in workouts %}
                {% if w.workoutId == workout.workoutId %}
                <li>
                  <div class="card grey lighten-3">                    
                      <div class="card-content">                        
                        <span class="card-title activator center-align white-text" style="background-color: #000000"><b>{{ workout.name|title }}</b><i class="material-icons right tooltipped" data-position="bottom" data-tooltip="Click for Instructions">more_vert</i></span>                          
                        <div class="divider grey darken-4"></div>
                        <div class="row left-align">
                          <p><b>Workouts Details:</b></p>
                          <div class="divider grey darken-4"></div>
                          <br>
                            <div class="col s6">
                                <p><strong>Name: {{w.name}}</strong></p>
                                <p>Weight: {{ workout.weight }}</p>
                                <p>Sets: {{ workout.sets}}</p>
                                <p>Reps: {{ workout.reps }}</p>
                            </div>
                            <div class="col s2"></div>                
                            <div class="col s6">
                                <p>Equipment: {{ w.equipment  }}</p>
                                <p>Target Muscle: {{ w.muscle }}</p>
                                <p>Type: {{ w.type }}</p>                                
                            </div>
                        </div>
                        <div class="divider grey darken-4"></div>                          
                        <div class="card-action">                                    
                          <a class="modal-trigger waves-effect waves-red btn" id="actbtn" href="#modal1" data-workout-id="{{ workout.uwId }}" data-workout-name="{{ w.name }}">Edit</a>
                          <a class="waves-effect waves-red btn" id="actbtn" href="/myworkouts/{{ workout.uwId }}">Delete</a>
                        </div>                                                                   
                      </div>
                      <div class="card-reveal grey lighten-3 left-align">
                        <span class="card-title text-darken-4 center-align white-text" style="background-color: #808080; font-size:medium" >{{ workout.name }}<i class="material-icons right">close</i></span>
                        <p>{{ w.instructions }}</p>
                      </div>                    
                  </div>
                </li>
                {% endif %}
                {% endfor %}                
                {% endfor %}
              </ul>
            </div>
          </li>
          {% endfor %}
        </ul>
      
      
    <!-- Repeat section for Wednesday through Sunday -->    
    <div id="modal1" class="modal" >
      <div class="modal-content">
        <h4 id="modal-title" class="center-align"></h4>
        <div class="divider grey darken-4"></div>
        <form method="POST" action="{{ url_for('myworkouts_views.editWorkout')}}" id="editForm">
          <input type="hidden" id="workoutId" name="workoutId" value="1">
          <div class="row">
            <div class="col s12 m6 input-field ">
              <input id="pname" type="text" name ="pname" class="validate" style="background-color:#d4d4d4; border-radius: 20px; border: 2px solid #dfd3d3;" >
              <label for="pname">Personal Name</label>
            </div>
            <div class="col s12 m6 input-field rounded">
              <input id="weight" type="text" name="weight" class="validate" style="background-color:#d4d4d4; border-radius: 20px; border: 2px solid #dfd3d3;">
              <label for="weight">Weight</label>
            </div>
          </div>
          <div class="row">
            <div class="col s12 m6 input-field">
              <input id="sets" type="number" name ="sets" class="validate"  style="background-color:#d4d4d4; border-radius: 20px; border: 2px solid #dfd3d3;">
              <label for="sets">Sets</label>
            </div>
            <div class="col s12 m6 input-field">
              <input id="reps" type="number" name ="reps" class="validate"  style="background-color:#d4d4d4; border-radius: 20px; border: 2px solid #dfd3d3;">
              <label for="reps">Reps</label>
            </div>
          </div>
          <div class="divider grey darken-4"></div>
          <p>Days:</p>
          {% for day, value in w_days.items() %}
          <label>
            <input type="radio" name="day" value="{{ value }}" />
            <span>{{ day }}</span>
          </label>
          {% endfor %}
          
          <label>
            <input type="radio" name="public" value="remove" />
            <span>Remove From Public Listing</span>
          </label>
          <label>
            <input type="radio" name="public" value="add" />
            <span>Add to Public Listing</span>
          </label>
         
          <div class="divider grey darken-4"></div>
          <div class="modal-footer" >
            <button id="actbtn" type="submit" class="waves-effect waves-green btn" >Edit</button>
            <a href="#!" id="actbtn" class="modal-close waves-effect waves-green btn">Cancel</a>
          </div>
        </form>
      </div>
    </div>
</main>
<div class="parallax-container" id="banner_b">
  <div class="parallax"><img src="https://i.imgur.com/W8LXHbD.jpg"></div>  
</div>
{% endblock %}